name: ie-bank-backend

on:
  push:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  BACKEND_WEBAPP_DEV: chiaradigi-be-dev
  BACKEND_WEBAPP_UAT: chiaradigi-be-uat
  RESOURCE_GROUP: aguadamillas_students_1
  APPINSIGHTS_DEV: group1-ai
  APPINSIGHTS_UAT: group1-ai-uat
  CHANNEL_ID: 'C066QRSD15E'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV: ghci

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8 pytest
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tests/unit -v
        python -m pytest tests/functional -v
        python -m pytest --cov=iebank_api --cov-report=xml:coverage.xml
    - name: Upload artifact for deployment jobs
      uses: actions/upload-artifact@v2
      with:
        name: python-app
        path: .

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Application Insights Instrumentation Key for Dev
      run: |
        APPINSIGHTS_KEY_DEV=$(az monitor app-insights component show --app ${{ env.APPINSIGHTS_DEV }} --resource-group ${{ env.RESOURCE_GROUP }} --query instrumentationKey -o tsv)
        echo "APPINSIGHTS_INSTRUMENTATIONKEY=$APPINSIGHTS_KEY_DEV" >> $GITHUB_ENV

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.BACKEND_WEBAPP_DEV }}
        package: .
      env:
        APPINSIGHTS_INSTRUMENTATIONKEY: ${{ env.APPINSIGHTS_INSTRUMENTATIONKEY }}

    - name: Post deployment status to Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ env.CHANNEL_ID }}
        slack-message: "Deployment to DEV completed: ${{ job.status }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

  deploy-uat:
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment:
      name: 'User Acceptance Testing'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: python-app
        path: .
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get Application Insights Instrumentation Key for UAT
      run: |
        APPINSIGHTS_KEY_UAT=$(az monitor app-insights component show --app ${{ env.APPINSIGHTS_UAT }} --resource-group ${{ env.RESOURCE_GROUP }} --query instrumentationKey -o tsv)
        echo "APPINSIGHTS_INSTRUMENTATIONKEY=$APPINSIGHTS_KEY_UAT" >> $GITHUB_ENV

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.BACKEND_WEBAPP_UAT }}
        package: .
      env:
        APPINSIGHTS_INSTRUMENTATIONKEY: ${{ env.APPINSIGHTS_INSTRUMENTATIONKEY }}

    - name: Post deployment status to Slack
      uses: slackapi/slack-github-action@v1.24.0
      with:
        channel-id: ${{ env.CHANNEL_ID }}
        slack-message: "Deployment to UAT completed: ${{ job.status }}"
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
